site:
  title: Placeholder Course Title
  start_page: placeholder-course-name::index.adoc

content:
  sources:
  - url: .
    start_path: content

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./content/supplemental-ui
